package com.task05.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBGeneratedUuid;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.UUID;

@DynamoDBTable(tableName = "cmtr-11cc74e9-Events-test")
public class Event {

  @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
  private UUID id;
  private Long principalId;
  private String createdAt;
  private Map<String, String> body;

  public Event(Long principalId, Map<String, String> body) {
    this.principalId = principalId;
    this.createdAt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSXXX").format(
        ZonedDateTime.now());
    this.body = body;
  }

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  @Override
  public String toString() {
    return "Event{" +
        "id=" + id +
        ", principalId=" + principalId +
        ", createdAt='" + createdAt + '\'' +
        ", body=" + body +
        '}';
  }

  public Long getPrincipalId() {
    return principalId;
  }

  public void setPrincipalId(Long principalId) {
    this.principalId = principalId;
  }

  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Map<String, String> getBody() {
    return body;
  }

  public void setBody(Map<String, String> body) {
    this.body = body;
  }
}
